export enum IconEnum {
  ADD = 'ant-design:plus-outlined',
  ADD_FOLD = 'ant-design:folder-add-outlined',
  AUTH = 'ant-design:safety-certificate-outlined',
  DELETE = 'ant-design:delete-outlined',
  DOWNLOAD = 'ant-design:cloud-download-outlined',
  EDIT = 'clarity:note-edit-line',
  EXPORT = 'ant-design:vertical-align-bottom-outlined',
  IMPORT = 'ant-design:vertical-align-top-outlined',
  LOG = 'ant-design:exception-outlined',
  PASSWORD = 'ant-design:key-outlined',
  PREVIEW = 'ant-design:eye-outlined',
  RESET = 'ant-design:sync-outlined',
  SEARCH = 'ant-design:search-outlined',
  SEND = 'ant-design:send-outlined',
  SETTING = 'ant-design:setting-outlined',
  TEST = 'ant-design:deployment-unit-outlined',
  UPLOAD = 'ant-design:cloud-upload-outlined',
  VIEW = 'ant-design:file-search-outlined',
}
